<?xml version="1.0" encoding="utf-8"?><Database Name="FacialRecMgmtDB" Class="FacialRecMgmtDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-OVL1JFQ;Initial Catalog=FacialRecMgmtDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FacialRecMgmtDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PatientProfile" Member="PatientProfiles">
    <Type Name="PatientProfile">
      <Column Name="PatientID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ProfilePicture" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PreCalFaceEncoding" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdmissionsCorePopulated" Member="AdmissionsCorePopulateds">
    <Type Name="AdmissionsCorePopulated">
      <Column Name="PatientID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdmissionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdmissionStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AdmissionEndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AdmissionsCorePopulated_LabsCorePopulated" Member="LabsCorePopulateds" ThisKey="PatientID,AdmissionID" OtherKey="PatientID,AdmissionID" Type="LabsCorePopulated" />
      <Association Name="AdmissionsCorePopulated_AdmissionsDiagnosesCorePopulate" Member="AdmissionsDiagnosesCorePopulates" ThisKey="PatientID,AdmissionID" OtherKey="PatientID,AdmissionID" Type="AdmissionsDiagnosesCorePopulate" />
      <Association Name="PatientCorePopulated_AdmissionsCorePopulated" Member="PatientCorePopulated" ThisKey="PatientID" OtherKey="PatientID" Type="PatientCorePopulated" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LabsCorePopulated" Member="LabsCorePopulateds">
    <Type Name="LabsCorePopulated">
      <Column Name="PatientID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AdmissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LabName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="LabValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LabUnits" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LabDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AdmissionsCorePopulated_LabsCorePopulated" Member="AdmissionsCorePopulated" ThisKey="PatientID,AdmissionID" OtherKey="PatientID,AdmissionID" Type="AdmissionsCorePopulated" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientCorePopulated" Member="PatientCorePopulateds">
    <Type Name="PatientCorePopulated">
      <Column Name="PatientID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientGender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PatientDateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PatientRace" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PatientMaritalStatus" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PatientLanguage" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PatientPopulationPercentageBelowPoverty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PatientCorePopulated_AdmissionsCorePopulated" Member="AdmissionsCorePopulateds" ThisKey="PatientID" OtherKey="PatientID" Type="AdmissionsCorePopulated" />
    </Type>
  </Table>
  <Table Name="dbo.AdmissionsDiagnosesCorePopulate" Member="AdmissionsDiagnosesCorePopulates">
    <Type Name="AdmissionsDiagnosesCorePopulate">
      <Column Name="PatientID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AdmissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryDiagnosisCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryDiagnosisDescription" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="AdmissionsCorePopulated_AdmissionsDiagnosesCorePopulate" Member="AdmissionsCorePopulated" ThisKey="PatientID,AdmissionID" OtherKey="PatientID,AdmissionID" Type="AdmissionsCorePopulated" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>